### PR TITLE
Make the stardust loop

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR loops the stardust fall. It also removes a bad Windows file.

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
@by003, I have created a GIMP script that creates a flake effect:

snow

Lots of things can be customized: the number of frames, the number of flakes, the min to max speed, the min to max wind, the min to max rotation, the min to max flake size, the shape, color and opacity of the flakes.

And of course, it loops.

Do I apply it to the stardust to make the effect more realistic?

**Comment by misiokles** [comment]
It would be great! 
One day I wanted to make something similar effects in vanilla towns, but my lack of skills :/
https://www.youtube.com/watch?v=eF0RqRPM9kA
https://www.youtube.com/watch?v=CvlDe2Qae9E

**Comment by by003** [comment]
@Fabrice-TIERCELIN  Cool, it's amazing. I am pretty sure it will be suitable in asylum screen. 
However, it might be a little confused because of the building 'stardust falls' . I cannot confirm which position is better for replacing this animation.

**Comment by Fabrice-TIERCELIN** [comment]
Actually, I wanted to say to redraw the stardust fall using this script, not adding a second particle fall.

**Comment by by003** [comment]
I agree with redrawing the stardust fall if it becomes better.

**Comment by Fabrice-TIERCELIN** [comment]
Done
The motion of the particles is more fluid

**Pull request merged**
