### PR TITLE
Rework the portrait of Alach

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR changes the portrait of Alach because too many heroes look front of the camera. It also fixes a typo.

Alternative version:
HPL000PF
HPS000PF

PS: What about removing [this repo](https://github.com/vcmi-mods/asylum)?

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, if I recycle the [Tenria campaign](https://github.com/vcmi-mods/new-pavilion/pull/32) changing the musics, the videos and the maps 90% generated 10% manual to fit, let's say, _Asylum_, would it be accepted?

**Comment by misiokles** [comment]
Such questions of course are for Ben Yan (I can't ping him there :(

**Comment by Fabrice-TIERCELIN** [comment]
It also can be done for a abandoned town mod

**Comment by GeorgeK1ng** [comment]
> Such questions of course are for Ben Yan (I can't ping him there :(

@by003

**Comment by Fabrice-TIERCELIN** [comment]
Don't bother Ben Yan. I know Misiokles. It's just a polite and implicite way to say "no" 😁

So closed subject

**Comment by misiokles** [comment]
Nooo... Ben Yan is active developer and his mod. And I'm just tired at discord channels to talk with people why main themes were chnaged. People are sensitive for such music changes, much more than graphics. So I want to get clear permissions.

**Comment by Fabrice-TIERCELIN** [comment]
Ah, OK, open subject

**Comment by by003** [comment]
Fine to fix portraits

**Pull request merged**
